name: Executar Node.js

on:
  push:
    branches:
      - main # Executa quando há push na branch "main"
  workflow_dispatch: # Permite execução manual

jobs:
  nodejs-job:
    runs-on: ubuntu-latest

    steps:
      # Configura o repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Especifica a versão do Node.js

      # Instala dependências
      - name: Instalar dependências
        run: npm install

      # Executa o script Node.js
      - name: Executar script Node.js
        run: node script.js # Substitua "script.js" pelo nome do seu arquivo
